service:
  name: torretechtest

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: ${opt:stage, 'dev'}

functions:
  search:
    handler: handler.search
    events:
      - http:
          method: get
          path: search/{searchTerm}
          cors: true

  getProfile:
    handler: handler.queryProfile
    events:
      - http:
          method: get
          path: profile/{profile}
          cors: true
  
  getConnections:
    handler: handler.queryConnections
    events:
      - http:
          method: get
          path: connections/{profile}
          cors: true

