service:
  name: torretechtest
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  stage: ${opt:stage, 'dev'}

functions:
  search:
    handler: handler.search
    events:
      - http:
          method: get
          path: search/{searchTerm}

  getProfile:
    handler: handler.queryProfile
    events:
      - http:
          method: get
          path: profile/{profile}
  
  getConnections:
    handler: handler.queryConnections
    events:
      - http:
        method: get
        path: connections/{profile}

